### ISSUE TITLE
Issue with test ARK resolution

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/n2t-admin#4]
According to

https://wiki.lyrasis.org/display/ARKs/ARK+Shoulders+FAQ#ARKShouldersFAQ-IsthereaquickwaytogetstartedcreatingtestARKs?

this resolution attempt
    https://n2t.net/ark:/99999/912148_testxyz

should redirect to
    https://ark.bnf.fr/ark:/99999/912148_testxyz

But it's not working. Here's what I get instead (using curl to illustrate):
![Screen Shot 2022-09-13 at 9 12 47 AM](https://user-images.githubusercontent.com/45110557/189952910-8829b363-d934-4ebd-b1fb-b7c9ac801271.png)

**Comment by datadavev** [comment]
This appears to be an issue with the apache configuration. The rewrite rule for `99999` is redirecting to the internal server address of `https://n2t.net:18443/...` instead of `https://n2t.net/...`. The internal address is not accessible by a client, hence the failure.

I suspect this rule in `rewrite2-server.conf`:
```
RewriteRule ^/ark:/?(99999[^/]*/9([^_]+)_.*)$ "/ark:/$2/$1" [NC,R=302]
```
needs to be functionally equivalent to:
```
RewriteRule ^/ark:/?(99999[^/]*/9([^_]+)_.*)$ "https://n2t.net/ark:/$2/$1" [NC,R=302]
```

**Comment by datadavev** [comment]
This fix works on dev by editing `/apps/n2t/sv/cur/apache2/conf/rewrite2-server.conf`:
Replace the rewrite rule:
```
# YYY this rule works for all registered NAANs
# This permits local resolvers to publish test/fake 99999-based ARKs via N2T
RewriteRule ^/ark:/?(99999[^/]*/9([^_]+)_.*)$ "/ark:/$2/$1" [NC,R=302]
```
with 
```
RewriteRule ^/ark:/?(99999[^/]*/9([^_]+)_.*)$ "%{REQUEST_SCHEME}://%{SERVER_NAME}/ark:/$2/$1" [NC,R=302]
```
After apache restart, the request works as expected, first redirecting to an expanded N2T address, which then handles the redirect to the expected target:
```
htrace -m https://n2t-dev.n2t.net/ark:/99999/912148_testxyz
> GET: https://n2t-dev.n2t.net/ark:/99999/912148_testxyz
< 302 https://n2t-dev.n2t.net/ark:/12148/99999/912148_testxyz
< 0.3390 sec
> GET: https://n2t-dev.n2t.net/ark:/12148/99999/912148_testxyz
< 302 http://ark.bnf.fr/ark:/12148/99999/912148_testxyz
< 0.0841 sec
> GET: http://ark.bnf.fr/ark:/12148/99999/912148_testxyz
< 400 text/html;charset=utf-8
< 0.2035 sec
SUMMARY: Start URL: https://n2t-dev.n2t.net/ark:/99999/912148_testxyz
SUMMARY: Final URL: http://ark.bnf.fr/ark:/12148/99999/912148_testxyz
SUMMARY: Start: 2022-12-02T13:40:38+0000
SUMMARY: Num requests: 3
SUMMARY: Elapsed: 0.626 seconds
```

That config file make be rewritten during n2t rebuilds, so need to find the source location and edit to make the change persistent.

**Comment by datadavev** [comment]
Looks like `rewrite2-server.conf` is generated by n2t with `minder_builder`. The corresponding line to change is currently [#74](https://github.com/CDLUC3/n2t-eggnog/blob/146ca60ce94ba2f635ef6f53dcc5d90529f571b6/t/n2t/minder_builder#L74): 
```
# YYY this rule works for all registered NAANs
# This permits local resolvers to publish test/fake 99999-based ARKs via N2T
RewriteRule ^/ark:/?(99999[^/]*/9([^_]+)_.*)\$ "/ark:/\$2/\$1" [NC,R=302]
```

**Comment by datadavev** [comment]
Flow diagrams for a bit more explanation. 

Incorrect behavior of N2T for test identifiers on servers other than N2T:

![](https://www.planttext.com/api/plantuml/svg/dP4z2y8m48Rt_ehRd6nexT1c445S5OhYABKziHWJIQxL-kjDRFr4KBpnkEVzI4Q6CatLNdZUmg26_X2cuTm_uff3YaQ96Y7JEyuIDom9mY2ALuI6JitPwquxwaVYpQCeDUO4f80vx7h-cPMA45HjKzxnfJMtiTqkLzAGhd8oiAc4W4eBA6Mkj9CNpNDMr_JLUajqC9mn6P8laNWGHz7WMvxRWxLoVqayAhKYapITfHp6cUoHQoHTFc-4ih1VT040)

Correct functionality, N2T redirects the user to another N2T address for the full lookup, which then redirects to the remote target:

![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuN9CBialKWWjJYtY0X4AkdOAVaOXUkMfILOA6IKb1SLM-lfvHYLwUQab-eb5sLRwbY2WRsbeP6XY4L-IMbnIKLd51TK2rMsb49HQd9zJbgg0LmUANK6fAPb5gSab2YNv2c2BmCe9sWPoCwfcR8x6OnPHdYREBHW-nwyDf_TXBW0QePUKbwQNLaHSoECE2w9CSaZDIm6c2000)
